name:                linear-talk
version:             0.1.0.0
github:              "githubuser/lc-2018-linear-types"
license:             BSD3
author:              "Ryan Orendorff, Daniel Hensley"
maintainer:          "ryan@orendorff.io"
copyright:           "2018 Ryan Orendorff and Daniel Hensley"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/lc-2018-linear-types>

dependencies:
- base >= 4.7 && < 5
- time
- text==1.2.3.0
- ghc-prim==0.5.2.0
- containers==0.5.11.0

library:
  source-dirs:
    - .
    - src

tests:
  linear-talk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - linear-talk
