# This resolver is required for the linear GHC extension
resolver: ghc-8.5
compiler: ghc-8.5
system-ghc: true

packages:
- .

# Dependencies mostly for linear-base
extra-deps:

# Tells stack to use Tweag's GHC docker image.
docker:
  enable: true
  image: tweag/linear-types:0.1.8
  #image: tweag/linear-types@sha256:6f68b8e02c2cd9e495af7826a13cd7c98e6503f8fab7d93a495d2b1676e9f336
